INSERT INTO course(id, course_year, title) VALUES (1, 'BACHELOR_FIRST', '1 курс');
INSERT INTO course(id, course_year, title) VALUES (2, 'BACHELOR_SECOND', '2 курс');
INSERT INTO course(id, course_year, title) VALUES (3, 'BACHELOR_THIRD', '3 курс');
INSERT INTO course(id, course_year, title) VALUES (4, 'BACHELOR_FOURTH', '4 курс');

INSERT INTO student_group VALUES (5, '11-701', 1);
INSERT INTO student_group VALUES (6, '11-702', 1);
INSERT INTO student_group VALUES (7, '11-703', 1);
INSERT INTO student_group VALUES (8, '11-704', 1);
INSERT INTO student_group VALUES (9, '11-705', 1);
INSERT INTO student_group VALUES (10, '11-706', 1);
INSERT INTO student_group VALUES (11, '11-707', 1);
INSERT INTO student_group VALUES (12, '11-708', 1);
INSERT INTO student_group VALUES (13, '11-601', 2);
INSERT INTO student_group VALUES (14, '11-602', 2);
INSERT INTO student_group VALUES (15, '11-603', 2);
INSERT INTO student_group VALUES (16, '11-604', 2);
INSERT INTO student_group VALUES (17, '11-605', 2);
INSERT INTO student_group VALUES (18, '11-606', 2);
INSERT INTO student_group VALUES (19, '11-607', 2);
INSERT INTO student_group VALUES (20, '11-608', 2);
INSERT INTO student_group VALUES (21, '11-501', 3);
INSERT INTO student_group VALUES (22, '11-502', 3);
INSERT INTO student_group VALUES (23, '11-503', 3);
INSERT INTO student_group VALUES (24, '11-504', 3);
INSERT INTO student_group VALUES (25, '11-505', 3);
INSERT INTO student_group VALUES (26, '11-506', 3);
INSERT INTO student_group VALUES (27, '11-507', 3);
INSERT INTO student_group VALUES (28, '11-508', 3);
INSERT INTO student_group VALUES (29, '11-401', 4);
INSERT INTO student_group VALUES (30, '11-402', 4);
INSERT INTO student_group VALUES (31, '11-403', 4);
INSERT INTO student_group VALUES (32, '11-404', 4);
INSERT INTO student_group VALUES (33, '11-405', 4);
INSERT INTO student_group VALUES (34, '11-406', 4);
INSERT INTO student_group VALUES (35, '11-407', 4);
INSERT INTO student_group VALUES (36, '11-408', 4);

INSERT INTO question(id, question_type, required, title) VALUES (1, 'RADIO', true, 'Посещаемость преподавателем занятий');
INSERT INTO question(id, question_type, required, title) VALUES (2, 'RADIO', true, 'Владение предметом');
INSERT INTO question(id, question_type, required, title) VALUES (3, 'RADIO', true, 'Доступность изложения материала');
INSERT INTO question(id, question_type, required, title) VALUES (4, 'RADIO', true, 'Актуальность и увлекательность курса');
INSERT INTO question(id, question_type, required, title) VALUES (5, 'RADIO', true, 'Ответы на вопросы студентов');
INSERT INTO question(id, question_type, required, title) VALUES (6, 'RADIO', true, 'Прослушали ли бы вы следующий курс у данного преподавателя?');
INSERT INTO question(id, question_type, required, title) VALUES (6, 'TEXT', false, 'Дополнительные комментарии по данному преподавателю');

INSERT INTO question_question_option (question_id, question_option) VALUES (1, '1');
INSERT INTO question_question_option (question_id, question_option) VALUES (1, '2');
INSERT INTO question_question_option (question_id, question_option) VALUES (1, '3');
INSERT INTO question_question_option (question_id, question_option) VALUES (1, '4');
INSERT INTO question_question_option (question_id, question_option) VALUES (1, '5');
INSERT INTO question_question_option (question_id, question_option) VALUES (1, 'Не могу оценить');
INSERT INTO question_question_option (question_id, question_option) VALUES (2, '1');
INSERT INTO question_question_option (question_id, question_option) VALUES (2, '2');
INSERT INTO question_question_option (question_id, question_option) VALUES (2, '3');
INSERT INTO question_question_option (question_id, question_option) VALUES (2, '4');
INSERT INTO question_question_option (question_id, question_option) VALUES (2, '5');
INSERT INTO question_question_option (question_id, question_option) VALUES (2, 'Не могу оценить');
INSERT INTO question_question_option (question_id, question_option) VALUES (3, '1');
INSERT INTO question_question_option (question_id, question_option) VALUES (3, '2');
INSERT INTO question_question_option (question_id, question_option) VALUES (3, '3');
INSERT INTO question_question_option (question_id, question_option) VALUES (3, '4');
INSERT INTO question_question_option (question_id, question_option) VALUES (3, '5');
INSERT INTO question_question_option (question_id, question_option) VALUES (3, 'Не могу оценить');
INSERT INTO question_question_option (question_id, question_option) VALUES (4, '1');
INSERT INTO question_question_option (question_id, question_option) VALUES (4, '2');
INSERT INTO question_question_option (question_id, question_option) VALUES (4, '3');
INSERT INTO question_question_option (question_id, question_option) VALUES (4, '4');
INSERT INTO question_question_option (question_id, question_option) VALUES (4, '5');
INSERT INTO question_question_option (question_id, question_option) VALUES (4, 'Не могу оценить');
INSERT INTO question_question_option (question_id, question_option) VALUES (5, 'Да');
INSERT INTO question_question_option (question_id, question_option) VALUES (5, 'Нет');
INSERT INTO question_question_option (question_id, question_option) VALUES (5, 'Не знаю');